// sql.js
var SQL = {}

SQL['USER'] = {
	"register" : "INSERT INTO USER (ACCOUNT, PASSWORD, CREATE_TIME) VALUES (?, ?, ?)",
	"login" : "SELECT * FROM USER WHERE ACCOUNT = ? AND PASSWORD = ?", 
}

SQL['RESTAURANT'] = {
	"query" : "SELECT * FROM RESTAURANT WHERE USER_ID = ?",
	"add" : "INSERT INTO RESTAURANT (USER_ID, RESTAURANT_NAME) VALUES (? ,?)",
	"del" : "DELETE FROM RESTAURANT WHERE USER_ID = ? AND ID = ?",
	"del_logic" : "UPDATE RESTAURANT SET IS_DELETE = ? WHERE RESTAURANT = ?",
}

module.exports = SQL;
