// sql.js
var SQL = {}

SQL['USER'] = {
	"register" : "INSERT INTO USER (ACCOUNT, PASSWORD, CREATE_TIME) VALUES (?, ?, ?)",
	"login" : "SELECT * FROM USER WHERE ACCOUNT = ? AND PASSWORD = ?", 
}

SQL['RESTAURANT'] = {
	"query" : "SELECT * FROM RESTAURANT WHERE USER_ID = ?",
	"add" : "INSERT INTO RESTAURANT (USER_ID, RESTAURANT_NAME, CREATE_TIME, IS_DELETE) VALUES (? ,? ,? ,?)",
	"del" : "DELETE FROM RESTAURANT WHERE RESTAURANT_NAME = ?",
	"del_logic" : "UPDATE RESTAURANT SET IS_DELETE = ? WHERE RESTAURANT = ?",
}

module.exports = SQL;
